name: Deploy main branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      EXPLORE_BEGIN_TOPIC_ARN: ${{ secrets.EXPLORE_BEGIN_TOPIC_ARN }}
      EXPLORE_END_TOPIC_ARN: ${{ secrets.EXPLORE_END_TOPIC_ARN }}
      QUEUE_URL: ${{ secrets.QUEUE_URL }}
      QUEUE_ARN: ${{ secrets.QUEUE_ARN }}
      WEBHOOK_TOPIC_ARN: ${{ secrets.WEBHOOK_TOPIC_ARN }}
      PLATFORM_URL: ${{ secrets.PLATFORM_URL }}
      SCRAPE_TOPIC_ARN: ${{ secrets.SCRAPE_TOPIC_ARN }}
      EXPLORE_DONE_TOPIC_ARN: ${{ secrets.EXPLORE_DONE_TOPIC_ARN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: "Use Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - name: serverless deploy
        uses: serverless/github-action@v4.0.0
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
