name: Deploy master branch

on:
  pull_request:
    branches:
      - main    
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: "Use Bun"
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - run: bun install --frozen-lockfile
    - name: serverless deploy
      uses: serverless/github-action@v4.0.0
      with:
        args: deploy
      env:
  
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
