name: Run tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      TEST_SCRAP_CALLBACK_URL: ${{ secrets.TEST_SCRAP_CALLBACK_URL }}
      TEST_SCRAP_API_KEY: ${{ secrets.TEST_SCRAP_API_KEY }}

    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: "Use Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: "Install dependencies"
        run: bun install --frozen-lockfile
      - name: "Run tests"
        run: bun test
